### ISSUE TITLE
Phpstorm插件模块冲突

### ISSUE THREAD

**Issue by spenice** [SmartInput/SmartInput#12]
![image](https://github.com/SmartInput/SmartInput/assets/40162682/a2e7e32e-3951-4723-a73d-43a7c509c3d0)
我安装的4.4.2-general 版本
安装后提示这个
怎么解决呢亲

**Comment by spenice** [comment]
![image](https://github.com/SmartInput/SmartInput/assets/40162682/fe6cff32-634b-48c4-b65e-d7fba9ef60e7)

**Comment by xxxtai** [comment]
已经解决
