### ISSUE TITLE
有个bug，大佬

### ISSUE THREAD

**Issue by xhyym** [SmartInput/SmartInput#13]
当我在js里面单引号或者双引号输入an的拼音的时候会自动切换英文输入法

**Comment by xxxtai** [comment]
你好，你使用的插件版本是什么发自我的手机-------- 原始邮件 --------发件人： xhyym ***@***.***>日期： 2024年1月18日周四 上午9:30收件人： SmartInput/SmartInput ***@***.***>抄送： Subscribed ***@***.***>主    题： [SmartInput/SmartInput] 有个bug，大佬 (Issue #13)
当我在js里面单引号或者双引号输入an的拼音的时候会自动切换英文输入法

**Comment by xhyym** [comment]
s是这个版本





、作伴
***@***.***







                       
原始邮件
                       
                     

发件人："xxxtai"< ***@***.*** &gt;;

发件时间：2024/1/18 10:05

收件人："SmartInput/SmartInput"< ***@***.*** &gt;;

抄送人："xhyym"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [SmartInput/SmartInput] 有个bug，大佬 (Issue #13)




 你好，你使用的插件版本是什么发自我的手机-------- 原始邮件 --------发件人： xhyym ***@***.***&gt;日期： 2024年1月18日周四 上午9:30收件人： SmartInput/SmartInput ***@***.***&gt;抄送： Subscribed ***@***.***&gt;主    题： [SmartInput/SmartInput] 有个bug，大佬 (Issue #13) 
 当我在js里面单引号或者双引号输入an的拼音的时候会自动切换英文输入法

**Comment by xhyym** [comment]
![image](https://github.com/SmartInput/SmartInput/assets/59786372/1fbf7723-964b-45fe-84a8-daeed729c5a7)

**Comment by xxxtai** [comment]
已经解决
