### ISSUE TITLE
插件全功能失效

### ISSUE THREAD

**Issue by WPF-8236** [SmartInput/SmartInput#2]
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023

SmartInput #4.1.1-idea

Windows 10  #19044.3086

日志UUID ：856F2D9E-E850-3CA1-72A6-50EBF6BBFE16

插件功能无任何响应，无任何报错提示，idea未报插件错误

**Comment by WPF-8236** [comment]
能否将 SmartInput #3.4.0 的版本支持更新一下

**Comment by xxxtai** [comment]
下载最新版本试下发自我的手机-------- 原始邮件 --------发件人： WPF-8236 ***@***.***>日期： 2023年7月27日周四 下午2:40收件人： SmartInput/SmartInput ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [SmartInput/SmartInput] 插件全功能失效 (Issue #2)
能否将 SmartInput #3.4.0 的版本支持更新一下
