### ISSUE TITLE
搜索时不能切换输入法，我想切换到中文，一输入马上会被切换成英文

### ISSUE THREAD

**Issue by iven98** [SmartInput/SmartInput#4]

**Comment by xxxtai** [comment]
我看下这个问题发自我的手机-------- 原始邮件 --------发件人： iven ***@***.***>日期： 2023年9月4日周一 下午2:01收件人： SmartInput/SmartInput ***@***.***>抄送： Subscribed ***@***.***>主    题： [SmartInput/SmartInput] 搜索时不能切换输入法，我想切换到中文，一输入马上会被切换成英文 (Issue #4)
