### ISSUE TITLE
插件无法切换输入法

### ISSUE THREAD

**Issue by Swiftlyfisher** [SmartInput/SmartInput#5]
win11， IDEA 2023.2.2
输入法选择的微软拼音，插件无法切换微软自带的输入法

**Comment by xxxtai** [comment]
你好，公众号上联系下我，帮你排查一下问题发自我的手机-------- 原始邮件 --------发件人： Swiftlyfisher ***@***.***>日期： 2023年9月26日周二 上午9:06收件人： SmartInput/SmartInput ***@***.***>抄送： Subscribed ***@***.***>主    题： [SmartInput/SmartInput] 插件无法切换输入法 (Issue #5)
win11， IDEA 2023.2.2
输入法选择的微软拼音，插件无法切换微软自带的输入法

**Comment by Swiftlyfisher** [comment]
找到问题了，如果我处于拼音输入法那么会帮我切换中英文
![image](https://github.com/SmartInput/SmartInput/assets/57713868/a4aa7c23-6f7d-4a2b-91e6-93327d0e0b10)
如果我处于纯英文输入法则无法切换回拼音
![image](https://github.com/SmartInput/SmartInput/assets/57713868/e3fa27fa-0a8a-43a8-b772-4e9ce06abcc1)
![image](https://github.com/SmartInput/SmartInput/assets/57713868/50d126d3-f1e3-449a-8d21-af7d9f7594de)
