### ISSUE TITLE
特意登陆上来评论，麻烦解绑arthas hot swap插件

### ISSUE THREAD

**Issue by itsxun** [SmartInput/SmartInput#8]
开发需要的是确定性，我需要一个确定的当前输入法，而不是自以为是的你认为我需要什么输入法当前，你们可以继续坚持你们的好想法，但是麻烦解绑idea arthas hot swap插件，谢谢。

**Comment by xxxtai** [comment]
你好，我也是arthas hotswap的作者，我免费提供使用arthas hotswap，期望借此推广另外一个插件，如果你不喜欢，你可以上arthas hotswap  github下载离线安装纯净版发自我的手机-------- 原始邮件 --------发件人： itsxun ***@***.***>日期： 2023年10月31日周二 中午11:44收件人： SmartInput/SmartInput ***@***.***>抄送： Subscribed ***@***.***>主    题： [SmartInput/SmartInput] 特意登陆上来评论，麻烦解绑arthas hot swap插件 (Issue #8)
开发需要的是确定性，我需要一个确定的当前输入法，而不是自以为是的你认为我需要什么输入发当前，你们可以继续坚持你们的好想法，但是麻烦解绑idea arthas hot swap插件，谢谢。

**Comment by xxxtai** [comment]
ok
